site_name: Somshubra Majumdar
theme:
  name: 'material'
  palette:
    primary: 'white'
    accent: 'light blue'
  feature:
    - tabs
    - instant
  icon:
    logo: material/github
    repo: material/github
docs_dir: docs/
repo_name: 'Repositories'
repo_url: https://github.com/titu1994/
site_url: http://titu1994.github.com
site_description: 'Personal site'

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: 'https://github.com/titu1994/'
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/HaseoX94/'
    - icon: 'fontawesome/brands/linkedin'
      link: 'https://www.linkedin.com/in/somshubramajumdar/'

plugins:
  - search:
      lang:
        - en

dev_addr: '0.0.0.0:8000'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  - pymdownx.superfences

nav:
- Home:
  - Info: index.md
  - Academia: academia.md
  - Contact: contact.md
- Research:
  - Published: research/published.md
  - Preprints: research/preprints.md
- Projects:
  - Deep Learning:
    - Neural Style Transfer: projects/dl/style-transfer.md
    - Image Super-Resolution : projects/dl/super-resolution.md
    - Image Classifiers: projects/dl/image-classifiers.md
    - Time Series Classification: projects/dl/time-series-classification.md
    - Neural Architecture Search: projects/dl/nas.md
    - Tensorflow: projects/dl/tensorflow.md
    - Keras Contrib: projects/dl/contrib.md
    - Additional Work: projects/dl/additional.md
  - Android: projects/android.md
